### ISSUE TITLE
Should we rename impl.py to something better?

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#10]
@afgane The current file organisation has impl.py, resources.py and services.py.
However, our conceptual organisation says that we have 3 types of objects: providers, resources and services. (http://cloudbridge.readthedocs.org/en/latest/concepts.html)

impl.py somehow doesn't seem to quite fit. We could rename it to provider.py, which is not that bad, since that is the core provider implementation, and it would make things consistent with the conceptual overview. However, if using provider.py muddies the water with the general concept of a provider as the overarching entity, should it be something like core.py or something?

**Comment by afgane** [comment]
I was also of the opinion `impl.py` wasn't great but never came up with a better alternative. Most obvious one would be `provider.py` but you've already discussed the drawbacks of it. However, only *providers* is used in the code so perhaps *provider* is still ok. Maybe `connection.py` instead?

**Comment by afgane** [comment]
Closed via 151b04d0fd70fb8e77397d8e56556d22522c82a2.
