### ISSUE TITLE
Azure security group rule handling is problematic

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#106]
In Azure, the default security group rules are returned separately from user created rules. The current implementation only returns the user created rules. However, this causes this line: https://github.com/gvlproject/cloudbridge/blob/ed2587017fbc7af197aabc28c46be612faf93663/test/test_security_service.py#L172 of the test to fail, because there is no default outbound rule.

If we merge in the existing default rules however, it causes this line: https://github.com/gvlproject/cloudbridge/blob/ed2587017fbc7af197aabc28c46be612faf93663/test/test_security_service.py#L191 to fail. This is because, in Azure, default security group rules cannot be deleted, as documented here: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-nsg#default-rules

Instead, they have a concept of priority which allows security group rules to be overridden, with defaults having the lowest priority. Just documenting all this here because it looks like we'll need to put in some effort to come up with a more consistent design.

**Comment by afgane** [comment]
Summary of discussion:
Internally create a complement of the default rules to effectively negate them, creating an equal environment as with the other providers. Further, filter those implicit rules automatically within the `list` (and `delete` methods) so the user never sees those rules (as long as they're interacting with Azure through CloudBridge).

**Comment by nuwang** [comment]
Closed by: https://github.com/gvlproject/cloudbridge/issues/106
