### ISSUE TITLE
Should we make keypair a mandatory parameter when launching instances?

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#107]
Currently, Azure requires the keypair as a mandatory parameter when launching an instance. The tests have been altered to support this. Maybe we need to make keypair a mandatory parameter?

**Comment by nuwang** [comment]
Also related: https://github.com/gvlproject/cloudbridge/issues/49

**Comment by afgane** [comment]
Yes.

**Comment by nuwang** [comment]
We now leave the keypair optional as is but generate a temp key for Azure during launch, if none has been provided: https://github.com/gvlproject/cloudbridge/commit/c18d898c6091527e8f2a9bf91f09bcf81b2a5ca3
