### ISSUE TITLE
[aws provider] moto library not available!

### ISSUE THREAD

**Issue by VJalili** [gvlproject/cloudbridge#119]
Using cloudbridge in Galaxy to download data from AWS, I see the following message in terminal: 

```shell
[aws provider] moto library not available!
```
It does not look like an error, as I cloudbridge can still upload/download data to/from AWS S3. However, I was wondering if that is an issue that should worry me, or I can ignore it. 

Just in case, here is how I'm using cloudbridge: 

```python
from cloudbridge.cloud.factory import CloudProviderFactory, ProviderList

aws_config = {'aws_access_key': ..., 'aws_secret_key': ...}
connection = CloudProviderFactory().create_provider(ProviderList.AWS, aws_config)
container_obj = connection.object_store.get(container_name)
key = container_obj.get(obj)
key.save_content(a_tmp_filename)
```

**Comment by nuwang** [comment]
It's an old debug message: https://github.com/gvlproject/cloudbridge/blob/d40eb16fa2510c8f51c184cc0dcf38182bf50951/cloudbridge/cloud/providers/aws/provider.py#L14

It's been fixed a while back to use log.debug, but we haven't made a recent release yet with that fix. It's safe to ignore it.

**Comment by VJalili** [comment]
Thanks. 
I am using `0.3.3` version.
