### ISSUE TITLE
Add extra provider initialization settings

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#12]
s3_port, s3_url, ec2_port, url etc.
Ditto for OpenStack.

**Comment by afgane** [comment]
Is this a2b3c9bdedaf7490499fa44d01d83915679218c9 what you had in mind for OpenStack? It works (and finally allows use of Chameleon cloud since it has no object store service) but I guess the same should be for all the services, which will get kind of messy with all the env vars.

**Comment by nuwang** [comment]
This looks good to me. I was originally thinking of something else though, which was to provide additional options for specifying API version numbers and other service specific settings we may have missed for the various OpenStack services. (e.g. cinder has OS_VOLUME_API_VERSION so neutron should probably have something similar)

**Comment by afgane** [comment]
There's a bunch of parameters for the connection object (e.g., Neutron example https://github.com/openstack/python-neutronclient/blob/master/neutronclient/v2_0/client.py#L106; Swift example: https://github.com/openstack/python-swiftclient/blob/master/swiftclient/client.py#L1285), yet none are in the same category as the API version example you mention. Do we really want to expose all of those params?

**Comment by afgane** [comment]
Re. the per-service credentials I added fro Swift - it doesn't look to me like we need any other such implementation. Swift can be independent of Nova but Cinder, Neutron and Keystone all work in sync with Nova (e.g., can't have a volume in a diff cloud than a VM). What do you think?

**Comment by nuwang** [comment]
I think things are fairly ok at this stage - we can revisit later if required.
