### ISSUE TITLE
Volumes and Snapshots do not have some required properties

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#13]
Volumes need:
size
description?
creation_time
attachment information
placement
tags

Snapshots need:
size
description?
creation_time
progress
tags

**Comment by gsrajadh** [comment]
@nuwang Can I work on this?

**Comment by nuwang** [comment]
@gsrajadh You'd be most welcome! For the "progress" field in a Snapshot, it would be good if you can check whether Google Compute Engine supports it too.

**Comment by nuwang** [comment]
Closed by:
https://github.com/gvlproject/cloudbridge/commit/eb939eba5ff9e8825c76d8aabcbaba66e0e15e5e
