### ISSUE TITLE
Zones don't have an internal representation/implementation

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#14]
The following code returns a Zone object native to the provider vs. a Cloudbridge native object.
```
>>> r = provider.compute.regions.list()[0]
>>> r.zones
[<AvailabilityZone: nova>]  # OpenStack native object
```

A complication related to this is that AWS does not provide a Zone listing endpoint.

**Comment by nuwang** [comment]
Fixed in commit: https://github.com/gvlproject/cloudbridge/commit/3bfeddd108920bcbedcdd2c9729abb32fe47d2a8
