### ISSUE TITLE
Support for specifying subnet?

### ISSUE THREAD

**Issue by MatthewRalston** [gvlproject/cloudbridge#2]
Hi, will this software support launching instances into subnets (or whatever the generic equivalent would be)?

**Comment by nuwang** [comment]
Yes. That's definitely on the cards. At the moment, work has not been started on that front, but any suggestions/contributions are welcome.

**Comment by afgane** [comment]
A preliminary implementation for private networks has been added at this point. Until we put together some docs, take a look at the [add_network_iterface](https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/interfaces/resources.py#L394) method.
