### ISSUE TITLE
Use boto3

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#22]
The AWS implementation uses the 'old' boto library. Replace it with [boto3](https://github.com/boto/boto3). Besides being the future version of the library, getting this library closer to [v0.2](https://github.com/gvlproject/cloudbridge/issues/9), it will allow much better filtering of returned results than the current implementation.

**Comment by 01000101** [comment]
I've started working on this in a fork branch but it might take a while. https://github.com/01000101/cloudbridge/tree/boto3-upgrade

**Comment by afgane** [comment]
Excellent! Thanks for the heads up and let us know if you’d like some help along the way to help with the volume of work.

**Comment by bradstimpson** [comment]
@afgane and @01000101 how are you progressing with this? I put my work on #23 on hold

**Comment by afgane** [comment]
Looks like this has been on pause of a few weeks now... @01000101 - could you please share your plans - even if it's to bail on the effort?

**Comment by 01000101** [comment]
A lot has been done and it's pretty close to usable. Tests won't work
(obviously) anymore and I wasn't planning on rewriting the tests as well.

**Comment by afgane** [comment]
Absolutely - it's a huge amount of code already! We can rework the tests after it's all in. So what's your thinking now - ready to do the PR or do a bit more work? Primarily to give @bradstimpson a feeling what to do with this effort.

**Comment by 01000101** [comment]
I'm travelling for the next 3 days but I might be able to find a little
time to finish up the last piece (VMs) if wifi permits. Once the VM object
is working (I think all of the other objects are done) I'll make a PR.

**Comment by afgane** [comment]
Hacktoberfest is over but I was wondering if you were still interested in wrapping this up perhaps?
Thanks.

**Comment by 01000101** [comment]
Yes, I am. I'm working on it now and as soon as I get the instance tests to
complete successfully, I'll make a PR to a new branch for everyone to
review and improve on.

**Comment by nuwang** [comment]
Done in https://github.com/gvlproject/cloudbridge/pull/77
