### ISSUE TITLE
No return value for instance.terminate()

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#25]
The library docs say when `instance.terminate()` method is called, we should get a `True`/`False` return value (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/interfaces/resources.py#L514). However, AWS and OpenStack implementations do not adhere to that interface (OS: https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/providers/openstack/resources.py#L297; AWS: https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/providers/aws/resources.py#L282)

The issue is that short of `get`-ing the just-deleted instance, there doesn't seem to be a good way of getting that info. So should we `get` the instance or modify the interface?

**Comment by nuwang** [comment]
@afgane I'm thinking we should modify the interface and just return void?

**Comment by nuwang** [comment]
Fixed in: https://github.com/gvlproject/cloudbridge/commit/922e0a0af1b5716840bcbb100c11637b1df87b30
