### ISSUE TITLE
Remaining featureset for release 0.1

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#3]
- [x] Update package organization
- [x] Remove lib versions from factory in favor of releases
- [x] Block device mapping
- [x] Support for launching instances into VPC/Neutron
- [x] Add iterators/generators 
- [x] 95%+ test coverage
- [x] Basic docs: getting started (e.g., provider configs, env variables), tutorials (e.g., launch an instance, add block storage), API docs
- [x] Implement support for networking objects (Networks & Subnets)
- [ ] Explicitly set all versions on dependencies
- [x] *Optional:* Paging and limits
- [x] *Optional:* Add more `__eq__` methods

**Comment by nuwang** [comment]
I've added a basic iterator implementation, but I'm not too happy with it. A lot of AWS methods don't support paging at all, so you end up having to implement it on the client-side. The current implementation is very basic and not very efficient when that happens.
