### ISSUE TITLE
Routers leaking implementation details

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#34]
Cloud specific code in:
https://github.com/gvlproject/cloudbridge/blob/13539ccda9e4809082796574d18b1b9bb3f2c624/test/test_network_service.py#L189

and:
https://github.com/gvlproject/cloudbridge/blob/13539ccda9e4809082796574d18b1b9bb3f2c624/test/test_compute_service.py#L378

**Comment by afgane** [comment]
Fixing this as part of a larger networking setup redo to remove provider-specific handling and provide more consistent abstractions. Here is a rough todo:

- [ ] Move `provider.network` services one level deeper to `provider.networking.networks`; include `provider.networking.subnets` service.
- [ ] Update tests
- [ ] Update docs relevant to the above steps
- [ ] Add `RouterService` (also under `networking`)
- [ ] Rename `router.attach_network` method to `router.attach_subnet`
- [ ] Add `GatewaysService` (under `networking`) and `InternetGateway` resource
- [ ] Add tests
- [ ] Add docs about the new features/resources and update existing procedures
- [ ] Update projects using CloudBridge networking code to use the new API structure
  - [ ] CloudLaunch
  - [ ] Galaxy ObjectStore? (ping @VJalili)
  - [ ] PR #51 
  - [ ] [GCE branch](https://github.com/gvlproject/cloudbridge/tree/gce)

**Comment by VJalili** [comment]
The current implementation of Galaxy ObjectStore does not leverage on the networking features of the cloudbridge. So, I guess it would be safe from Galaxy stand-point to make these changes.

**Comment by afgane** [comment]
The interface has been updated so when GCE is merged forward it will account for the necessary changes.
