### ISSUE TITLE
Version Conflict when trying to run tox tests.

### ISSUE THREAD

**Issue by MartinPaulo** [gvlproject/cloudbridge#37]
If I clone the repository, setup the needed environment and then run tox, it fails under both py27 and py36 (I haven't tried pypy), with the following error message:

```bash
running test
Searching for requests!=2.12.2,!=2.13.0,>=2.10.0
# removed lines
Best match: requests 2.12.5
# removed lines
pkg_resources.VersionConflict: (Babel 2.4.0 (/home/travis/build/gvlproject/cloudbridge/.tox/py27-aws/lib/python2.7/site-packages), Requirement.parse('Babel!=2.4.0,>=2.3.4'))
```

Working through the dependencies in `setup.py` it would appear that indeed the version of requests that best fits them is 2.12.5. Which is why it is then downloaded and installed. However, that version of requests in turn explicitly states that it requires Babel==2.3.4 and not the version Babel==2.4.0 that has already been installed. Instant end of run :(

**Comment by MartinPaulo** [comment]
My simple fix for this is to change `setup.py` to add the two required libraries:

```python
openstack_reqs = ['requests==2.12.5', 'Babel==2.3.4',
                  'python-novaclient==7.0.0',
                  'python-glanceclient>=2.5.0,<=2.6.0',
                  'python-cinderclient>=1.9.0,<=2.0.1',
                  'python-swiftclient>=3.2.0,<=3.3.0',
                  'python-neutronclient>=6.0.0,<=6.1.0',
                  'python-keystoneclient>=3.8.0,<=3.10.0']
```

Running the tests with this change in place gets them running. I'm not sure this is the best fix, though.

**Comment by MartinPaulo** [comment]
I've dug into this a bit more - given my Java background this has been good learning. Sadly I can't find a better way, other than setting ranges on the two libraries (e.g.: `'requests<2.13.0', 'Babel>=2.3.4,<2.4.0'`)

**Comment by nuwang** [comment]
@MartinPaulo Would you mind issuing a pull request for this?

**Comment by MartinPaulo** [comment]
@nuwang No problem: will do

**Comment by nuwang** [comment]
@MartinPaulo Thanks for fixing this. Closing issue.
