### ISSUE TITLE
The tests expect block storage to be available in all zones

### ISSUE THREAD

**Issue by MartinPaulo** [gvlproject/cloudbridge#39]
As written, the tests for the block store service expect block storage to be available in the same default zone as the instance created. On our nectar cloud this is not necessarily true: block storage for a given project may only be available in one of the zones. Hence the tests attempt to create block storage in the same default zone as the instance will most often fail.

**Comment by afgane** [comment]
This looks like it was fixed in #40 so closing the issue.
