### ISSUE TITLE
GCEInstanceService.find returns a list of instances

### ISSUE THREAD

**Issue by machristie** [gvlproject/cloudbridge#48]
InstanceService find method documentation says
```
        Searches for an instance by a given list of attributes.

        :rtype: ``object`` of :class:`.Instance`
        :return: an Instance object
```

However AWSInstanceService.find also returns a list, so I'm not sure if maybe this is a bug in the interface.  Since instance names should be unique it does make sense to me that find would only return a single instance (or None if not found).

**Comment by afgane** [comment]
This is actually a bug in the interface docs because, for the case of AWS and OpenStack, multiple instances can have the same name. `.get` method can be used to get a specific one. I'll update the docs in the interface.
