### ISSUE TITLE
test_crud_snapshot delete reverting

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#60]
OpenStack tests when run on Jetstream keep timing out lately and here's the where it happens although it's not at all clear why: https://github.com/gvlproject/cloudbridge/blob/master/test/test_block_store_service.py#L149

Adding a few print statements to that code:
```
print("\nDeleting snap %s (%s)" % (snap.name, snap.id))
snap.delete()
snap.refresh()
print("Deleted said snap (status: %s); waiting until gone" % snap.state)
snap.wait_for(
  [SnapshotState.UNKNOWN],
  terminal_states=[SnapshotState.ERROR])
print("cleanup snap gone")
```

the following is shown. OSS and `<Response>` bits I added in the OpenStack snap delete implementation (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/providers/openstack/resources.py#L665). 

```
Deleting snap cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 (3a47f71c-0364-4592-94ac-573e768a6572)
OSS deleting cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3
OSS deleted snap
<Response [202]>
Deleted said snap; waiting until gone
Will wait for cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 (configuring) to reach ['unknown']
Object cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 in state configuring. Waiting for ['unknown']...
Object cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 in state available. Waiting for ['unknown']...
Object cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 in state available. Waiting for ['unknown']...
Object cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 in state available. Waiting for ['unknown']...
Object cb_snap-cb_crudsnap-c937cd55-4cac-41e8-a80b-681959c740d3 in state available. Waiting for ['unknown']...
... REPEATS INDEFINITELY
```

`configuring` state is a mapped from OS's `deleting` state (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/providers/openstack/resources.py#L591), so it looks like for some reason it reverts back to `available`. The silly part is that afterwards, the snapshot can be manually deleted (using CloudBridge or the dashboard).

The only discovery is that after not attempting to delete the snap during the test run and doing to manually afterwards, the snapshot gets stuck in `deleting` state (tried it 3 times). Given all of this, most likely it's an issue w/ Jetstream but logging it here for the record.

**Comment by nuwang** [comment]
This looks like an issue with Jetstream. Works fine on DevStack.

**Comment by nuwang** [comment]
Closing since this is probably a jetstream issue.
