### ISSUE TITLE
Limit AWS images to owner by default?

### ISSUE THREAD

**Issue by nuwang** [gvlproject/cloudbridge#75]
The AWS image service doesn't appear to provide any paging capabilities: https://stackoverflow.com/questions/24036068/how-to-limit-the-ouput-of-get-all-images-in-amazon-boto

This makes the tests run very slowly against AWS. Should we restrict these to the owner? or do something else?

**Comment by afgane** [comment]
The AWS dashboard lists _Owned by me_ images by default so I'd say that's a reasonable default for us as well. However, it's a bit undesirable that such filtering applies to AWS only though.

**Comment by nuwang** [comment]
I have this vague recollection that the GCE provider was running into similar issues. It makes sense I guess, since there are potentially thousands of images, and it doesn't make sense to page through them all - you'd typically want to find a particular image by name, architecture or some other attribute.

What if we do this? Calling list() by default adds the "Owned by me" filter. If you call find() though, that default filter is removed, and the user-specified filter takes effect.

**Comment by nuwang** [comment]
Conclusion: By default, list will show images belonging to the project. However, if you do a "find", it searches everything. Have parameter filter_by_owner=True/False

**Comment by afgane** [comment]
I added the filtering but I don't recall if we said the `filter_by_owner` should be added at the interface level and hence implemented for all the providers or something else?

**Comment by nuwang** [comment]
Yes, the conclusion was to add it at interface level for all providers for the list method, but remove it when doing a find etc.

**Comment by afgane** [comment]
Finished up with https://github.com/gvlproject/cloudbridge/commit/c7b46a3b4dfa02dabf1c994aad40df557faef5ad
