### ISSUE TITLE
Add services for Security Group rules and Floating IPs

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#83]
Managing Floating IPs and Security Groups is currently done via methods within the `NetworkService` (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/interfaces/services.py#L670) and the Security Group resource (https://github.com/gvlproject/cloudbridge/blob/master/cloudbridge/cloud/interfaces/resources.py#L1720), respectively. 

Instead, to keep the structure of the library consistent and provide a more intuitive interface, extract operations for those two resource types into their own dedicated services.

**Comment by nuwang** [comment]
Fixed in commits: https://github.com/gvlproject/cloudbridge/commit/175ee982db57b3833f892a04007d4829ec03a112 and https://github.com/gvlproject/cloudbridge/commit/22f5a152fe02e0617aacf667fcb04104da6d99c3
