### ISSUE TITLE
Future release features

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#9]
A list of features to be added in a future release:
- [x] Use [boto3](https://github.com/boto/boto3) for AWS backend (see #22)
- [ ] Increase test coverage to 97%
- [ ] Wrap all exceptions in cloudbridge equivalents
- [ ] Add support for Snapshot sharing
- [ ] Add Metadata service (see #23)

_BONUS_
- [ ] Add Google Cloud as a new provider (see [gce branch](https://github.com/gvlproject/cloudbridge/tree/gce))

**Comment by VJalili** [comment]
> Wrap all exceptions in cloudbridge equivalents

I would vote for this to get a higher priority ;-)

**Comment by nuwang** [comment]
Some possible strategies for wrapping exceptions and handling other cross-cutting concerns:

1. Do it individually at base class level
```
    def create(....):
        do_standard_logging()
        try:
             _create_impl()
        except Exception as e:
            if e instanceof CloudBridgeException:
               raise e
           else:
               raise CloudBridgeException(e)
```

2. Do it globally
https://stackoverflow.com/questions/16961914/python-logging-all-of-a-class-methods-without-decorating-each-one

3. Use an AOP library
https://stackoverflow.com/questions/286958/any-aop-support-library-for-python

**Comment by VJalili** [comment]
Given my .NET background, I prefer: 
- implement a concrete logic as to avoid exceptions as much as possible; basically you prevent or have multiple backup plans for exceptions.
- handle un-avoidable exceptions globally.
